=== ezavalar/MOOC_PRACTICA_JSON_Y_JSON_SCHEMA/banda.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": ".\\banda.schema.json",
    "type": "object",
    "properties": {
      "group": {
        "type": "string",
        "minLength": 2,
        "maxLength": 50
        },
      "foundation_year": {
        "type": "string",
        "format": "date"
        },
      "web": {
        "type": "string", 
        "format": "uri"
        },
      "email": {
        "type": "string",
        "format": "email"
        },
      "description": {
        "type": "string",
        "minLength": 50,
        "maxLength": 500
        },
      "members": {
        "type": "array",
        "minItems": 2,
        "maxItems":10,
        "uniqueItems": true,
        "items": {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "age": {"type": "integer"}
          },
          "required": ["name", "age"]
        }
      },
      "albums": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "year": {"type": "string"},
            "songs": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {"type": "string"},
                  "length": {"type": "string", "format": "duration"},
                  "hit": {"type": "boolean"}
                },
                "required": ["name", "length", "hit"]
              }
            }
          },
          "required": ["name", "year", "songs"]
        }
      },
      "concerts": {
        "type": "array", 
        "minItems": 1,
        "maxItems": 20,
        "uniqueItems": true,
        "items": {"type": "string"}
        }
    },
    "required": ["group", "foundation_year", "web", "email", "description", "members", "albums", "concerts"]
  }

=== ezavalar/MOOC_PRACTICA_JSON_Y_JSON_SCHEMA/banda.json
{
    "group": "Aerosmith",
    "foundation_year" : "1970-01-01",
    "web": "https://www.aerosmith.com/",
    "email": "ezavalar_isc@hotmail.com",
    "description": "Aerosmith es una banda estadounidense de rock formada en Boston en 1970. Sus miembros son: Steven Tyler (cantante), Joe Perry (guitarra), Tom Hamilton (bajo), Joey Kramer (bater√≠a) y Brad Whitford (guitarra).",
    "members": [
        {
            "name": "Steven Tyler",
            "age": 74
        },
        {
            "name": "Joe Perry",
            "age": 73
        },
        {
            "name": "Tom Hamilton",
            "age": 71
        },
        {
            "name": "Brad Whitford",
            "age": 71
        },
        {
            "name": "Joey Kramer",
            "age": 74
        }
    ],
    "albums":[
        {
            "name":"Get a Grip",
            "year":"1993",
            "songs": [{
                "name": "Cryin'",
                "length": "PT5M9S",
                "hit": true
            },
            {
                "name": "Flesh",
                "length": "PT5M57S",
                "hit": false
            }
        ]
        }
    ],
    "concerts": ["Detroit", "Chicago", "Washington", "Toronto", "Releigh", "Cleveland"]
}
